#!/usr/bin/env python3
"""Build and solve OpenFOAM flow for the accepted random periodic geometry."""

from __future__ import annotations

import json
import math
import os
import argparse
import copy
import shutil
import subprocess
import sys
import textwrap
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
os.environ.setdefault("MPLCONFIGDIR", str(ROOT / "outputs" / ".matplotlib"))
os.environ.setdefault("XDG_CACHE_HOME", str(ROOT / "outputs" / ".cache"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, Rectangle


OUT = ROOT / "outputs" / "random_openfoam_flow"
CASE = OUT / "case"
GEOMETRY_PATH = ROOT / "outputs" / "random_porous_geometry" / "random_porous_geometry.json"
FOAM = ROOT / "scripts" / "openfoam_docker.sh"

TARGET_M_PER_DAY = 4.0
UBAR = TARGET_M_PER_DAY / 86400.0
NU = 1.0e-6
BODY_ACCEL = float(os.environ.get("RANDOM_OPENFOAM_BODY_ACCEL", "7.44e-1"))
FORCING_MODE = os.environ.get("RANDOM_OPENFOAM_FORCING_MODE", "mean_velocity").lower()
Z_HALF = 2.0e-6
MESH_BACKEND = os.environ.get("RANDOM_OPENFOAM_MESH_BACKEND", "gmsh").lower()
GMSH = os.environ.get("RANDOM_OPENFOAM_GMSH", "gmsh")
GMSH_SIZE_WALL = float(os.environ.get("RANDOM_OPENFOAM_GMSH_SIZE_WALL", "3.0e-6"))
GMSH_SIZE_FAR = float(os.environ.get("RANDOM_OPENFOAM_GMSH_SIZE_FAR", "8.0e-6"))
GMSH_REFINE_DIST_MIN = float(os.environ.get("RANDOM_OPENFOAM_GMSH_REFINE_DIST_MIN", "8.0e-6"))
GMSH_REFINE_DIST_MAX = float(os.environ.get("RANDOM_OPENFOAM_GMSH_REFINE_DIST_MAX", "3.5e-5"))
TWO_D_EMPTY = os.environ.get("RANDOM_OPENFOAM_2D_EMPTY", "true").lower() in {"1", "true", "yes", "on"}
Z_CELLS = 1 if TWO_D_EMPTY else 4
BASE_CELLS_X = 180
BASE_CELLS_Y = 120
SURFACE_REFINEMENT = 2
END_TIME = 180
AUTO_ORIGIN_SHIFT = os.environ.get("RANDOM_OPENFOAM_ORIGIN_SHIFT", "auto" if MESH_BACKEND == "snappy" else "false")
SNAP_MESH = os.environ.get("RANDOM_OPENFOAM_SNAP", "false").lower() in {"1", "true", "yes", "on"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reuse-mesh", action="store_true", help="Reuse the existing mesh in the selected output case.")
    parser.add_argument("--out-name", default=OUT.name, help="Output subdirectory under outputs/.")
    parser.add_argument("--geometry-path", type=Path, default=GEOMETRY_PATH, help="Geometry JSON to convert to an OpenFOAM case.")
    parser.add_argument("--mesh-backend", choices=["gmsh", "snappy"], default=MESH_BACKEND)
    parser.add_argument("--gmsh-size-wall", type=float, default=GMSH_SIZE_WALL)
    parser.add_argument("--gmsh-size-far", type=float, default=GMSH_SIZE_FAR)
    parser.add_argument("--gmsh-refine-dist-min", type=float, default=GMSH_REFINE_DIST_MIN)
    parser.add_argument("--gmsh-refine-dist-max", type=float, default=GMSH_REFINE_DIST_MAX)
    parser.add_argument("--forcing-mode", choices=["mean_velocity", "body_force"], default=FORCING_MODE)
    parser.add_argument("--body-accel", type=float, default=BODY_ACCEL)
    parser.add_argument("--end-time", type=int, default=END_TIME)
    return parser.parse_args()


def configure_from_args(args: argparse.Namespace) -> None:
    global OUT, CASE, GEOMETRY_PATH, MESH_BACKEND, GMSH_SIZE_WALL, GMSH_SIZE_FAR
    global GMSH_REFINE_DIST_MIN, GMSH_REFINE_DIST_MAX, FORCING_MODE, BODY_ACCEL
    global END_TIME, AUTO_ORIGIN_SHIFT
    OUT = ROOT / "outputs" / args.out_name
    CASE = OUT / "case"
    GEOMETRY_PATH = args.geometry_path if args.geometry_path.is_absolute() else ROOT / args.geometry_path
    MESH_BACKEND = args.mesh_backend
    GMSH_SIZE_WALL = args.gmsh_size_wall
    GMSH_SIZE_FAR = args.gmsh_size_far
    GMSH_REFINE_DIST_MIN = args.gmsh_refine_dist_min
    GMSH_REFINE_DIST_MAX = args.gmsh_refine_dist_max
    FORCING_MODE = args.forcing_mode
    BODY_ACCEL = args.body_accel
    END_TIME = args.end_time
    if "RANDOM_OPENFOAM_ORIGIN_SHIFT" not in os.environ:
        AUTO_ORIGIN_SHIFT = "auto" if MESH_BACKEND == "snappy" else "false"


def foam_header(class_name: str, location: str, object_name: str) -> str:
    return textwrap.dedent(
        f"""\
        /*--------------------------------*- C++ -*----------------------------------*\\
        | OpenFOAM dictionary generated by scripts/run_random_openfoam_flow.py       |
        \\*---------------------------------------------------------------------------*/
        FoamFile
        {{
            version     2.0;
            format      ascii;
            class       {class_name};
            location    "{location}";
            object      {object_name};
        }}
        // ************************************************************************* //

        """
    )


def write_foam_file(path: Path, class_name: str, location: str, object_name: str, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(foam_header(class_name, location, object_name) + textwrap.dedent(body), encoding="utf-8")


def run(cmd: list[str], cwd: Path, log_name: str) -> None:
    log_path = OUT / log_name
    with log_path.open("w", encoding="utf-8") as log:
        log.write("$ " + " ".join(cmd) + "\n\n")
        log.flush()
        completed = subprocess.run(
            cmd,
            cwd=cwd,
            stdout=log,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
        )
    if completed.returncode != 0:
        tail = "\n".join(log_path.read_text(encoding="utf-8", errors="replace").splitlines()[-100:])
        raise RuntimeError(f"{cmd[0]} failed with code {completed.returncode}; tail of {log_path}:\n{tail}")


def load_geometry() -> dict:
    if not GEOMETRY_PATH.exists():
        raise FileNotFoundError(f"Missing geometry file: {GEOMETRY_PATH}")
    return prepare_openfoam_geometry(json.loads(GEOMETRY_PATH.read_text(encoding="utf-8")))


def best_periodic_cut(values: np.ndarray, radii: np.ndarray, length: float) -> tuple[float, float]:
    probes = np.linspace(0.0, length, 6000, endpoint=False)
    best_clearance = -np.inf
    best_cut = 0.0
    for cut in probes:
        d = np.abs(values - cut)
        d = np.minimum(d, length - d)
        clearance = float(np.min(d - radii))
        if clearance > best_clearance:
            best_clearance = clearance
            best_cut = float(cut)
    return best_cut, best_clearance


def periodic_images_for_grains(grains: list[dict], lx: float, ly: float) -> list[dict]:
    images = []
    for grain in grains:
        gid = int(grain["id"])
        cx = float(grain["x"])
        cy = float(grain["y"])
        radius = float(grain["radius"])
        for ix in (-1, 0, 1):
            for iy in (-1, 0, 1):
                x = cx + ix * lx
                y = cy + iy * ly
                if not (-radius <= x <= lx + radius and -radius <= y <= ly + radius):
                    continue
                images.append(
                    {
                        "name": f"grain_{gid:03d}_img_{ix:+d}_{iy:+d}".replace("+", "p").replace("-", "m"),
                        "grain_id": gid,
                        "image_i": ix,
                        "image_j": iy,
                        "x": x,
                        "y": y,
                        "radius": radius,
                    }
                )
    return images


def prepare_openfoam_geometry(data: dict) -> dict:
    geometry = copy.deepcopy(data)
    lx = float(geometry["domain"]["length_x"])
    ly = float(geometry["domain"]["length_y"])
    if AUTO_ORIGIN_SHIFT.lower() not in {"auto", "1", "true", "yes"}:
        geometry["periodic_images_for_openfoam"] = periodic_images_for_grains(geometry["grains"], lx, ly)
        geometry["openfoam_origin_shift"] = {"enabled": False, "x_cut": 0.0, "y_cut": 0.0}
        return geometry

    centers = np.array([[g["x"], g["y"]] for g in geometry["grains"]], dtype=float)
    radii = np.array([g["radius"] for g in geometry["grains"]], dtype=float)
    x_cut, x_clear = best_periodic_cut(centers[:, 0], radii, lx)
    y_cut, y_clear = best_periodic_cut(centers[:, 1], radii, ly)
    for grain in geometry["grains"]:
        grain["x"] = float((float(grain["x"]) - x_cut) % lx)
        grain["y"] = float((float(grain["y"]) - y_cut) % ly)
    geometry["periodic_images_for_openfoam"] = periodic_images_for_grains(geometry["grains"], lx, ly)
    geometry["openfoam_origin_shift"] = {
        "enabled": True,
        "x_cut": x_cut,
        "y_cut": y_cut,
        "x_boundary_clearance": x_clear,
        "y_boundary_clearance": y_clear,
        "note": "Coordinates shifted only for OpenFOAM so periodic boundaries cut through the least intrusive pore lines.",
    }
    return geometry


def periodic_delta(delta: np.ndarray | float, length: float) -> np.ndarray | float:
    return delta - length * np.round(delta / length)


def surface_clearance(
    x: np.ndarray,
    y: np.ndarray,
    centers: np.ndarray,
    radii: np.ndarray,
    lx: float,
    ly: float,
) -> np.ndarray:
    clearance = np.full_like(x, np.inf, dtype=float)
    for (cx, cy), radius in zip(centers, radii):
        dx = periodic_delta(x - cx, lx)
        dy = periodic_delta(y - cy, ly)
        clearance = np.minimum(clearance, np.sqrt(dx * dx + dy * dy) - radius)
    return clearance


def location_in_mesh(geometry: dict) -> tuple[float, float, float]:
    lx = float(geometry["domain"]["length_x"])
    ly = float(geometry["domain"]["length_y"])
    centers = np.array([[g["x"], g["y"]] for g in geometry["grains"]], dtype=float)
    radii = np.array([g["radius"] for g in geometry["grains"]], dtype=float)
    nx, ny = 420, 280
    x = (np.arange(nx) + 0.5) * lx / nx
    y = (np.arange(ny) + 0.5) * ly / ny
    xx, yy = np.meshgrid(x, y, indexing="ij")
    clearance = surface_clearance(xx, yy, centers, radii, lx, ly)
    idx = np.unravel_index(int(np.argmax(clearance)), clearance.shape)
    return float(xx[idx]), float(yy[idx]), 0.0


def gmsh_entity_list(values: list[int]) -> str:
    return ", ".join(str(value) for value in values)


def write_gmsh_geo(geometry: dict) -> None:
    """Write a body-fitted extruded Gmsh geometry for OpenFOAM import."""
    lx = float(geometry["domain"]["length_x"])
    ly = float(geometry["domain"]["length_y"])
    z0 = -Z_HALF
    thickness = 2.0 * Z_HALF
    eps = 5.0e-8

    disk_tags = []
    disk_lines = []
    for idx, image in enumerate(geometry["periodic_images_for_openfoam"], start=1):
        tag = 1000 + idx
        disk_tags.append(tag)
        disk_lines.append(
            f'Disk({tag}) = {{{float(image["x"]):.12g}, {float(image["y"]):.12g}, {z0:.12g}, '
            f'{float(image["radius"]):.12g}, {float(image["radius"]):.12g}}};'
        )

    disk_list = gmsh_entity_list(disk_tags)
    geo = f"""
SetFactory("OpenCASCADE");
Geometry.Tolerance = 1e-12;
Mesh.MshFileVersion = 2.2;
Mesh.Algorithm = 6;
Mesh.CharacteristicLengthMin = {GMSH_SIZE_WALL:.12g};
Mesh.CharacteristicLengthMax = {GMSH_SIZE_FAR:.12g};

Rectangle(1) = {{0, 0, {z0:.12g}, {lx:.12g}, {ly:.12g}, 0}};
{chr(10).join(disk_lines)}

fluid[] = BooleanDifference{{ Surface{{1}}; Delete; }}{{ Surface{{{disk_list}}}; Delete; }};
Coherence;

eps = {eps:.12g};
z0 = {z0:.12g};
z1 = {Z_HALF:.12g};
lx = {lx:.12g};
ly = {ly:.12g};
t = {thickness:.12g};

allCurves[] = Boundary{{ Surface{{fluid[]}}; }};
leftC[] = Curve In BoundingBox{{-eps, -eps, z0 - eps, eps, ly + eps, z0 + eps}};
rightC[] = Curve In BoundingBox{{lx - eps, -eps, z0 - eps, lx + eps, ly + eps, z0 + eps}};
bottomC[] = Curve In BoundingBox{{-eps, -eps, z0 - eps, lx + eps, eps, z0 + eps}};
topC[] = Curve In BoundingBox{{-eps, ly - eps, z0 - eps, lx + eps, ly + eps, z0 + eps}};
wallCurves[] = allCurves[];
wallCurves[] -= leftC[];
wallCurves[] -= rightC[];
wallCurves[] -= bottomC[];
wallCurves[] -= topC[];

Field[1] = Distance;
Field[1].CurvesList = {{wallCurves[]}};
Field[1].Sampling = 200;
Field[2] = Threshold;
Field[2].InField = 1;
Field[2].SizeMin = {GMSH_SIZE_WALL:.12g};
Field[2].SizeMax = {GMSH_SIZE_FAR:.12g};
Field[2].DistMin = {GMSH_REFINE_DIST_MIN:.12g};
Field[2].DistMax = {GMSH_REFINE_DIST_MAX:.12g};
Background Field = 2;

out[] = Extrude {{0, 0, t}} {{
  Surface{{fluid[]}};
  Layers{{1}};
  Recombine;
}};

allSurf[] = Boundary{{ Volume{{out[1]}}; }};
front[] = Surface In BoundingBox{{-eps, -eps, z0 - eps, lx + eps, ly + eps, z0 + eps}};
back[] = Surface In BoundingBox{{-eps, -eps, z1 - eps, lx + eps, ly + eps, z1 + eps}};
left[] = Surface In BoundingBox{{-eps, -eps, z0 - eps, eps, ly + eps, z1 + eps}};
right[] = Surface In BoundingBox{{lx - eps, -eps, z0 - eps, lx + eps, ly + eps, z1 + eps}};
bottom[] = Surface In BoundingBox{{-eps, -eps, z0 - eps, lx + eps, eps, z1 + eps}};
top[] = Surface In BoundingBox{{-eps, ly - eps, z0 - eps, lx + eps, ly + eps, z1 + eps}};
walls[] = allSurf[];
walls[] -= front[];
walls[] -= back[];
walls[] -= left[];
walls[] -= right[];
walls[] -= bottom[];
walls[] -= top[];

Physical Surface("front") = {{front[]}};
Physical Surface("back") = {{back[]}};
Physical Surface("left") = {{left[]}};
Physical Surface("right") = {{right[]}};
Physical Surface("bottom") = {{bottom[]}};
Physical Surface("top") = {{top[]}};
Physical Surface("walls") = {{walls[]}};
Physical Volume("fluid") = {{out[1]}};
"""
    (CASE / "system" / "random_porous.geo").write_text(textwrap.dedent(geo).strip() + "\n", encoding="utf-8")


def write_gmsh_patch_dicts(geometry: dict) -> None:
    lx = float(geometry["domain"]["length_x"])
    ly = float(geometry["domain"]["length_y"])
    z0 = -Z_HALF
    z1 = Z_HALF
    eps = 1.0e-8

    write_foam_file(
        CASE / "system" / "topoSetDict",
        "dictionary",
        "system",
        "topoSetDict",
        f"""
        actions
        (
            {{
                name    frontFaces;
                type    faceSet;
                action  new;
                source  boxToFace;
                box     ({-eps:.12g} {-eps:.12g} {z0 - eps:.12g}) ({lx + eps:.12g} {ly + eps:.12g} {z0 + eps:.12g});
            }}
            {{
                name    backFaces;
                type    faceSet;
                action  new;
                source  boxToFace;
                box     ({-eps:.12g} {-eps:.12g} {z1 - eps:.12g}) ({lx + eps:.12g} {ly + eps:.12g} {z1 + eps:.12g});
            }}
            {{
                name    leftFaces;
                type    faceSet;
                action  new;
                source  boxToFace;
                box     ({-eps:.12g} {-eps:.12g} {z0 - eps:.12g}) ({eps:.12g} {ly + eps:.12g} {z1 + eps:.12g});
            }}
            {{
                name    rightFaces;
                type    faceSet;
                action  new;
                source  boxToFace;
                box     ({lx - eps:.12g} {-eps:.12g} {z0 - eps:.12g}) ({lx + eps:.12g} {ly + eps:.12g} {z1 + eps:.12g});
            }}
            {{
                name    bottomFaces;
                type    faceSet;
                action  new;
                source  boxToFace;
                box     ({-eps:.12g} {-eps:.12g} {z0 - eps:.12g}) ({lx + eps:.12g} {eps:.12g} {z1 + eps:.12g});
            }}
            {{
                name    topFaces;
                type    faceSet;
                action  new;
                source  boxToFace;
                box     ({-eps:.12g} {ly - eps:.12g} {z0 - eps:.12g}) ({lx + eps:.12g} {ly + eps:.12g} {z1 + eps:.12g});
            }}
        );
        """,
    )

    write_foam_file(
        CASE / "system" / "createPatchDict",
        "dictionary",
        "system",
        "createPatchDict",
        """
        pointSync false;

        patches
        (
            {
                name front;
                patchInfo { type patch; }
                constructFrom set;
                set frontFaces;
            }
            {
                name back;
                patchInfo { type patch; }
                constructFrom set;
                set backFaces;
            }
            {
                name left;
                patchInfo { type patch; }
                constructFrom set;
                set leftFaces;
            }
            {
                name right;
                patchInfo { type patch; }
                constructFrom set;
                set rightFaces;
            }
            {
                name bottom;
                patchInfo { type patch; }
                constructFrom set;
                set bottomFaces;
            }
            {
                name top;
                patchInfo { type patch; }
                constructFrom set;
                set topFaces;
            }
        );
        """,
    )


def boundary_patch_entry(name: str, body: str, lx: float, ly: float) -> str:
    retained = []
    drop_prefixes = (
        "type",
        "physicalType",
        "inGroups",
        "matchTolerance",
        "transform",
        "neighbourPatch",
        "separationVector",
        "AMIMethod",
        "requireMatch",
        "lowWeightCorrection",
        "restartUncoveredSourceFace",
    )
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if any(stripped.startswith(prefix) for prefix in drop_prefixes):
            continue
        retained.append("        " + stripped)

    if name == "left":
        header = [
            "        type            cyclicAMI;",
            "        inGroups        1(cyclicAMI);",
            "        matchTolerance  0.0001;",
            "        transform       translational;",
            "        neighbourPatch  right;",
            f"        separationVector ({lx:.12g} 0 0);",
            "        AMIMethod       faceAreaWeightAMI;",
            "        requireMatch    false;",
            "        lowWeightCorrection 0.05;",
            "        restartUncoveredSourceFace false;",
        ]
    elif name == "right":
        header = [
            "        type            cyclicAMI;",
            "        inGroups        1(cyclicAMI);",
            "        matchTolerance  0.0001;",
            "        transform       translational;",
            "        neighbourPatch  left;",
            f"        separationVector ({-lx:.12g} 0 0);",
            "        AMIMethod       faceAreaWeightAMI;",
            "        requireMatch    false;",
            "        lowWeightCorrection 0.05;",
            "        restartUncoveredSourceFace false;",
        ]
    elif name == "bottom":
        header = [
            "        type            cyclicAMI;",
            "        inGroups        1(cyclicAMI);",
            "        matchTolerance  0.0001;",
            "        transform       translational;",
            "        neighbourPatch  top;",
            f"        separationVector (0 {ly:.12g} 0);",
            "        AMIMethod       faceAreaWeightAMI;",
            "        requireMatch    false;",
            "        lowWeightCorrection 0.05;",
            "        restartUncoveredSourceFace false;",
        ]
    elif name == "top":
        header = [
            "        type            cyclicAMI;",
            "        inGroups        1(cyclicAMI);",
            "        matchTolerance  0.0001;",
            "        transform       translational;",
            "        neighbourPatch  bottom;",
            f"        separationVector (0 {-ly:.12g} 0);",
            "        AMIMethod       faceAreaWeightAMI;",
            "        requireMatch    false;",
            "        lowWeightCorrection 0.05;",
            "        restartUncoveredSourceFace false;",
        ]
    elif name in {"front", "back"}:
        header = [
            "        type            empty;",
            "        inGroups        1(empty);",
        ]
    else:
        header = [
            "        type            wall;",
            "        inGroups        1(wall);",
        ]

    return f"    {name}\n    {{\n" + "\n".join(header + retained) + "\n    }"


def patch_gmsh_boundary_types(geometry: dict) -> None:
    boundary_path = CASE / "constant" / "polyMesh" / "boundary"
    text = boundary_path.read_text(encoding="utf-8")
    start = text.index("(\n")
    end = text.rindex("\n)")
    header_lines = text[:start].rstrip().splitlines()
    header_without_count = "\n".join(header_lines[:-1])
    blocks_text = text[start + 2 : end]
    lx = float(geometry["domain"]["length_x"])
    ly = float(geometry["domain"]["length_y"])

    blocks: list[tuple[str, str]] = []
    i = 0
    while i < len(blocks_text):
        while i < len(blocks_text) and blocks_text[i].isspace():
            i += 1
        if i >= len(blocks_text):
            break
        name_start = i
        while i < len(blocks_text) and not blocks_text[i].isspace() and blocks_text[i] != "{":
            i += 1
        name = blocks_text[name_start:i].strip()
        brace = blocks_text.index("{", i)
        depth = 0
        j = brace
        while j < len(blocks_text):
            if blocks_text[j] == "{":
                depth += 1
            elif blocks_text[j] == "}":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        blocks.append((name, blocks_text[brace + 1 : j]))
        i = j + 1

    patched = [boundary_patch_entry(name, body, lx, ly) for name, body in blocks if name != "fluid"]
    new_header = f"{header_without_count}\n\n{len(patched)}\n(\n"
    boundary_path.write_text(new_header + "\n".join(patched) + "\n)\n\n// ************************************************************************* //\n", encoding="utf-8")


def write_case(geometry: dict) -> None:
    if CASE.exists():
        shutil.rmtree(CASE)
    (CASE / "system").mkdir(parents=True)
    (CASE / "constant").mkdir()
    (CASE / "0").mkdir()

    lx = float(geometry["domain"]["length_x"])
    ly = float(geometry["domain"]["length_y"])
    z0 = -Z_HALF
    z1 = Z_HALF
    cyl_z0 = -5.0 * Z_HALF
    cyl_z1 = 5.0 * Z_HALF
    loc = location_in_mesh(geometry)
    z_boundary_type = "empty" if TWO_D_EMPTY else "symmetryPlane"
    if MESH_BACKEND not in {"gmsh", "snappy"}:
        raise ValueError(f"Unsupported RANDOM_OPENFOAM_MESH_BACKEND={MESH_BACKEND!r}")
    if MESH_BACKEND == "gmsh":
        write_gmsh_geo(geometry)
        write_gmsh_patch_dicts(geometry)

    write_foam_file(
        CASE / "system" / "blockMeshDict",
        "dictionary",
        "system",
        "blockMeshDict",
        f"""
        scale 1;

        vertices
        (
            (0 0 {z0:.12g})
            ({lx:.12g} 0 {z0:.12g})
            ({lx:.12g} {ly:.12g} {z0:.12g})
            (0 {ly:.12g} {z0:.12g})
            (0 0 {z1:.12g})
            ({lx:.12g} 0 {z1:.12g})
            ({lx:.12g} {ly:.12g} {z1:.12g})
            (0 {ly:.12g} {z1:.12g})
        );

        blocks
        (
            hex (0 1 2 3 4 5 6 7) ({BASE_CELLS_X} {BASE_CELLS_Y} {Z_CELLS}) simpleGrading (1 1 1)
        );

        edges ();

        boundary
        (
            left
            {{
                type cyclicAMI;
                neighbourPatch right;
                transform translational;
                separationVector ({lx:.12g} 0 0);
                matchTolerance 0.0001;
                AMIMethod faceAreaWeightAMI;
                requireMatch false;
                lowWeightCorrection 0.05;
                restartUncoveredSourceFace false;
                faces ((0 4 7 3));
            }}
            right
            {{
                type cyclicAMI;
                neighbourPatch left;
                transform translational;
                separationVector ({-lx:.12g} 0 0);
                matchTolerance 0.0001;
                AMIMethod faceAreaWeightAMI;
                requireMatch false;
                lowWeightCorrection 0.05;
                restartUncoveredSourceFace false;
                faces ((1 2 6 5));
            }}
            bottom
            {{
                type cyclicAMI;
                neighbourPatch top;
                transform translational;
                separationVector (0 {ly:.12g} 0);
                matchTolerance 0.0001;
                AMIMethod faceAreaWeightAMI;
                requireMatch false;
                lowWeightCorrection 0.05;
                restartUncoveredSourceFace false;
                faces ((0 1 5 4));
            }}
            top
            {{
                type cyclicAMI;
                neighbourPatch bottom;
                transform translational;
                separationVector (0 {-ly:.12g} 0);
                matchTolerance 0.0001;
                AMIMethod faceAreaWeightAMI;
                requireMatch false;
                lowWeightCorrection 0.05;
                restartUncoveredSourceFace false;
                faces ((3 7 6 2));
            }}
            front
            {{
                type {z_boundary_type};
                faces ((0 3 2 1));
            }}
            back
            {{
                type {z_boundary_type};
                faces ((4 5 6 7));
            }}
        );

        mergePatchPairs ();
        """,
    )

    geometry_lines = []
    surface_lines = []
    region_lines = []
    for image in geometry["periodic_images_for_openfoam"]:
        name = image["name"]
        cx = float(image["x"])
        cy = float(image["y"])
        radius = float(image["radius"])
        geometry_lines.append(
            f"""
            {name}
            {{
                type searchableCylinder;
                point1 ({cx:.12g} {cy:.12g} {cyl_z0:.12g});
                point2 ({cx:.12g} {cy:.12g} {cyl_z1:.12g});
                radius {radius:.12g};
            }}
            """
        )
        surface_lines.append(
            f"""
            {name}
            {{
                level ({SURFACE_REFINEMENT} {SURFACE_REFINEMENT});
                patchInfo {{ type wall; }}
            }}
            """
        )
        region_lines.append(
            f"""
            {name}
            {{
                mode distance;
                levels (({max(1.2e-5, 0.20 * radius):.12g} {SURFACE_REFINEMENT}));
            }}
            """
        )

    write_foam_file(
        CASE / "system" / "snappyHexMeshDict",
        "dictionary",
        "system",
        "snappyHexMeshDict",
        f"""
        castellatedMesh true;
        snap            {"true" if SNAP_MESH else "false"};
        addLayers       false;

        geometry
        {{
            {''.join(geometry_lines)}
        }}

        castellatedMeshControls
        {{
            maxLocalCells  3000000;
            maxGlobalCells 8000000;
            minRefinementCells 0;
            nCellsBetweenLevels 2;
            features ();

            refinementSurfaces
            {{
                {''.join(surface_lines)}
            }}

            resolveFeatureAngle 30;

            refinementRegions
            {{
                {''.join(region_lines)}
            }}

            locationInMesh ({loc[0]:.12g} {loc[1]:.12g} {loc[2]:.12g});
            allowFreeStandingZoneFaces true;
        }}

        snapControls
        {{
            nSmoothPatch 3;
            tolerance 2.0;
            nSolveIter 50;
            nRelaxIter 5;
            nFeatureSnapIter 10;
            implicitFeatureSnap true;
            explicitFeatureSnap false;
            multiRegionFeatureSnap false;
        }}

        addLayersControls
        {{
            relativeSizes true;
            layers {{}}
            expansionRatio 1.0;
            finalLayerThickness 0.3;
            minThickness 0.1;
            nGrow 0;
            featureAngle 60;
            nRelaxIter 3;
            nSmoothSurfaceNormals 1;
            nSmoothNormals 3;
            nSmoothThickness 10;
            maxFaceThicknessRatio 0.5;
            maxThicknessToMedialRatio 0.3;
            minMedialAxisAngle 90;
            nBufferCellsNoExtrude 0;
            nLayerIter 50;
        }}

        meshQualityControls
        {{
            #includeEtc "caseDicts/meshQualityDict"
            minVol 1e-30;
            minTetQuality -1e30;
            relaxed
            {{
                maxNonOrtho 75;
            }}
            nSmoothScale 4;
            errorReduction 0.75;
        }}

        debug 0;
        mergeTolerance 1e-6;
        """,
    )

    write_foam_file(
        CASE / "system" / "meshQualityDict",
        "dictionary",
        "system",
        "meshQualityDict",
        """
        #includeEtc "caseDicts/meshQualityDict"
        minVol 1e-30;
        minTetQuality -1e30;
        """,
    )

    write_foam_file(
        CASE / "system" / "controlDict",
        "dictionary",
        "system",
        "controlDict",
        f"""
        application     simpleFoam;
        startFrom       startTime;
        startTime       0;
        stopAt          endTime;
        endTime         {END_TIME};
        deltaT          1;
        writeControl    timeStep;
        writeInterval   {END_TIME};
        purgeWrite      0;
        writeFormat     ascii;
        writePrecision  10;
        writeCompression off;
        timeFormat      general;
        timePrecision   6;
        runTimeModifiable true;
        """,
    )

    write_foam_file(
        CASE / "system" / "fvSchemes",
        "dictionary",
        "system",
        "fvSchemes",
        """
        ddtSchemes
        {
            default steadyState;
        }

        gradSchemes
        {
            default Gauss linear;
            grad(U) cellLimited Gauss linear 1;
        }

        divSchemes
        {
            default none;
            div(phi,U) bounded Gauss linearUpwind grad(U);
            div((nuEff*dev2(T(grad(U))))) Gauss linear;
        }

        laplacianSchemes
        {
            default Gauss linear corrected;
        }

        interpolationSchemes
        {
            default linear;
        }

        snGradSchemes
        {
            default corrected;
        }

        wallDist
        {
            method meshWave;
        }
        """,
    )

    write_foam_file(
        CASE / "system" / "fvSolution",
        "dictionary",
        "system",
        "fvSolution",
        """
        solvers
        {
            p
            {
                solver GAMG;
                tolerance 1e-12;
                relTol 0.01;
                smoother GaussSeidel;
                nPreSweeps 0;
                nPostSweeps 2;
                cacheAgglomeration true;
                agglomerator faceAreaPair;
                nCellsInCoarsestLevel 10;
                mergeLevels 1;
            }

            pFinal
            {
                $p;
                relTol 0;
            }

            U
            {
                solver smoothSolver;
                smoother symGaussSeidel;
                tolerance 1e-13;
                relTol 0.05;
            }

            UFinal
            {
                $U;
                relTol 0;
            }
        }

        SIMPLE
        {
            consistent yes;
            nNonOrthogonalCorrectors 2;
            pRefCell 0;
            pRefValue 0;
            residualControl
            {
                p 1e-8;
                U 1e-10;
            }
        }

        relaxationFactors
        {
            fields
            {
                p 0.3;
            }
            equations
            {
                U 0.7;
            }
        }
        """,
    )

    write_foam_file(
        CASE / "constant" / "transportProperties",
        "dictionary",
        "constant",
        "transportProperties",
        f"""
        transportModel  Newtonian;
        nu              [0 2 -1 0 0 0 0] {NU:.12g};
        """,
    )

    write_foam_file(
        CASE / "constant" / "turbulenceProperties",
        "dictionary",
        "constant",
        "turbulenceProperties",
        """
        simulationType laminar;
        """,
    )

    write_force_options()

    cyclic_velocity = """
        {
            type cyclicAMI;
            value uniform (0 0 0);
        }
    """
    cyclic_pressure = """
        {
            type cyclicAMI;
        }
    """
    wall_regex = '"(grain_.*|walls|walls3d|defaultFaces)"'
    write_foam_file(
        CASE / "0" / "U",
        "volVectorField",
        "0",
        "U",
        f"""
        dimensions      [0 1 -1 0 0 0 0];
        internalField   uniform ({UBAR:.12g} 0 0);

        boundaryField
        {{
            "(left|right|bottom|top)" {cyclic_velocity}
            "(front|back)"
            {{
                type {z_boundary_type};
            }}
            {wall_regex}
            {{
                type noSlip;
            }}
        }}
        """,
    )

    write_foam_file(
        CASE / "0" / "p",
        "volScalarField",
        "0",
        "p",
        f"""
        dimensions      [0 2 -2 0 0 0 0];
        internalField   uniform 0;

        boundaryField
        {{
            "(left|right|bottom|top)" {cyclic_pressure}
            "(front|back)"
            {{
                type {z_boundary_type};
            }}
            {wall_regex}
            {{
                type zeroGradient;
            }}
        }}
        """,
    )


def write_force_options() -> None:
    if FORCING_MODE == "body_force":
        # Specific vector source in the momentum equation. This avoids the
        # meanVelocityForce feedback division that is brittle for imperfect AMI
        # screens; Stokes linearity lets downstream analyses rescale velocities.
        body = f"""
        bodyForce1
        {{
            type            vectorSemiImplicitSource;
            active          yes;
            selectionMode   all;
            volumeMode      specific;
            sources
            {{
                U           (({BODY_ACCEL:.12g} 0 0) 0);
            }}
        }}
        """
    else:
        body = f"""
        meanVelocityForce1
        {{
            type            meanVelocityForce;
            active          yes;
            selectionMode   all;
            Ubar            ({UBAR:.12g} 0 0);
            fields          (U);
            relaxation      1.0;
        }}
        """
    write_foam_file(
        CASE / "constant" / "fvOptions",
        "dictionary",
        "constant",
        "fvOptions",
        body,
    )


def remove_solution_times() -> None:
    if not CASE.exists():
        return
    for path in CASE.iterdir():
        if not path.is_dir() or path.name == "0":
            continue
        try:
            float(path.name)
        except ValueError:
            continue
        shutil.rmtree(path)


def run_openfoam_case(geometry: dict, reuse_mesh: bool = False) -> None:
    if not reuse_mesh:
        if MESH_BACKEND == "gmsh":
            mesh_path = CASE / "constant" / "random_porous.msh"
            print("Running gmsh system/random_porous.geo", flush=True)
            run(
                [
                    GMSH,
                    "system/random_porous.geo",
                    "-3",
                    "-format",
                    "msh2",
                    "-o",
                    str(mesh_path.relative_to(CASE)),
                ],
                CASE,
                "log.gmsh",
            )
            print("Running gmshToFoam", flush=True)
            run([str(FOAM), "gmshToFoam", str(mesh_path.relative_to(CASE))], CASE, "log.gmshToFoam")
            print("Running topoSet", flush=True)
            run([str(FOAM), "topoSet"], CASE, "log.topoSet")
            print("Running createPatch -overwrite", flush=True)
            run([str(FOAM), "createPatch", "-overwrite"], CASE, "log.createPatch")
            patch_gmsh_boundary_types(geometry)
            mesh_commands = [
                (["renumberMesh", "-overwrite"], "log.renumberMesh"),
                (["checkMesh", "-allTopology", "-allGeometry"], "log.checkMesh"),
            ]
        else:
            mesh_commands = [
                (["blockMesh"], "log.blockMesh"),
                (["snappyHexMesh", "-overwrite"], "log.snappyHexMesh"),
                (["checkMesh", "-allTopology", "-allGeometry"], "log.checkMesh"),
            ]
        for cmd, log_name in mesh_commands:
            print("Running " + " ".join(cmd), flush=True)
            run([str(FOAM), *cmd], CASE, log_name)

    commands = [
        (["simpleFoam"], "log.simpleFoam"),
        (["foamToVTK", "-latestTime", "-ascii", "-fields", "(U p)", "-no-boundary", "-no-point-data", "-overwrite"], "log.foamToVTK"),
    ]
    for cmd, log_name in commands:
        print("Running " + " ".join(cmd), flush=True)
        run([str(FOAM), *cmd], CASE, log_name)


def polygon_area_from_cell_points(xy: np.ndarray) -> float:
    rounded = np.unique(np.round(xy, decimals=14), axis=0)
    if rounded.shape[0] < 3:
        return float("nan")
    center = np.mean(rounded, axis=0)
    angles = np.arctan2(rounded[:, 1] - center[1], rounded[:, 0] - center[0])
    ordered = rounded[np.argsort(angles)]
    x = ordered[:, 0]
    y = ordered[:, 1]
    return float(0.5 * abs(np.dot(x, np.roll(y, -1)) - np.dot(y, np.roll(x, -1))))


def parse_xml_vtu(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    root = ET.parse(path).getroot()
    piece = root.find(".//Piece")
    if piece is None:
        raise ValueError(f"Could not find Piece element in {path}")

    points_node = piece.find("./Points/DataArray")
    if points_node is None or points_node.text is None:
        raise ValueError(f"Could not find point coordinates in {path}")
    points = np.fromstring(points_node.text, sep=" ", dtype=float).reshape(-1, 3)

    cells_node = piece.find("./Cells")
    if cells_node is None:
        raise ValueError(f"Could not find Cells element in {path}")
    cell_arrays = {node.attrib.get("Name", ""): node for node in cells_node.findall("./DataArray")}
    connectivity = np.fromstring(cell_arrays["connectivity"].text or "", sep=" ", dtype=int)
    offsets = np.fromstring(cell_arrays["offsets"].text or "", sep=" ", dtype=int)

    cell_data = piece.find("./CellData")
    if cell_data is None:
        raise ValueError(f"Could not find CellData in {path}")
    u_node = None
    for node in cell_data.findall("./DataArray"):
        if node.attrib.get("Name") == "U":
            u_node = node
            break
    if u_node is None or u_node.text is None:
        raise ValueError(f"Could not find cell-centered U in {path}")
    velocity = np.fromstring(u_node.text, sep=" ", dtype=float).reshape(-1, 3)

    n_cells = offsets.size
    centers = np.empty((n_cells, 3), dtype=float)
    areas = np.empty(n_cells, dtype=float)
    start = 0
    for c_id, stop in enumerate(offsets):
        ids = connectivity[start:stop]
        cell_points = points[ids]
        centers[c_id] = np.mean(cell_points, axis=0)
        areas[c_id] = polygon_area_from_cell_points(cell_points[:, :2])
        start = int(stop)
    return centers[:, :2], velocity[:, :2], areas


def find_vtu_file() -> Path:
    candidates = sorted((CASE / "VTK").glob("*/*.vtu"))
    internal = [p for p in candidates if p.name == "internal.vtu"]
    if internal:
        return internal[-1]
    if candidates:
        return candidates[-1]
    raise FileNotFoundError(f"No VTU files found under {CASE / 'VTK'}")


def read_log_tail(name: str, n: int = 30) -> str:
    path = OUT / name
    if not path.exists():
        return ""
    return "\n".join(path.read_text(encoding="utf-8", errors="replace").splitlines()[-n:])


def draw_flow_figure(geometry: dict, centers_xy: np.ndarray, velocity_xy: np.ndarray, areas: np.ndarray) -> dict:
    lx = float(geometry["domain"]["length_x"])
    ly = float(geometry["domain"]["length_y"])
    grains = geometry["grains"]
    centers = np.array([[g["x"], g["y"]] for g in grains], dtype=float)
    radii = np.array([g["radius"] for g in grains], dtype=float)
    pinned = np.array([bool(g.get("pinned", False)) for g in grains], dtype=bool)

    speed = np.linalg.norm(velocity_xy, axis=1)
    good = np.isfinite(speed) & np.isfinite(areas) & (areas > 0)
    mean_ux = float(np.sum(velocity_xy[good, 0] * areas[good]) / np.sum(areas[good]))
    mean_uy = float(np.sum(velocity_xy[good, 1] * areas[good]) / np.sum(areas[good]))
    mean_speed = float(np.sum(speed[good] * areas[good]) / np.sum(areas[good]))
    max_speed = float(np.nanmax(speed))

    fig, axes = plt.subplots(1, 2, figsize=(13.5, 5.2), dpi=180)
    ax = axes[0]
    triang = ax.tricontourf(
        centers_xy[:, 0],
        centers_xy[:, 1],
        speed / max(UBAR, 1.0e-30),
        levels=40,
        cmap="turbo",
    )
    fig.colorbar(triang, ax=ax, fraction=0.046, pad=0.02, label=r"$|\mathbf{u}|/\bar{u}$")
    for gid, ((cx, cy), radius) in enumerate(zip(centers, radii)):
        edge = "#f97316" if pinned[gid] else "#020617"
        lw = 1.6 if pinned[gid] else 0.5
        ax.add_patch(Circle((cx, cy), radius, fc="#111827", ec=edge, lw=lw))
    ax.set_title("OpenFOAM speed field")

    ax = axes[1]
    ax.add_patch(Rectangle((0.0, 0.0), lx, ly, fill=False, lw=1.5, ec="#111827"))
    for gid, ((cx, cy), radius) in enumerate(zip(centers, radii)):
        edge = "#f97316" if pinned[gid] else "#020617"
        lw = 1.6 if pinned[gid] else 0.5
        ax.add_patch(Circle((cx, cy), radius, fc="#111827", ec=edge, lw=lw))
        ax.text(cx, cy, str(gid), color="white", fontsize=5.0, ha="center", va="center")
    rng = np.random.default_rng(22)
    if centers_xy.shape[0] > 1800:
        sample = rng.choice(centers_xy.shape[0], size=1800, replace=False)
    else:
        sample = np.arange(centers_xy.shape[0])
    ax.quiver(
        centers_xy[sample, 0],
        centers_xy[sample, 1],
        velocity_xy[sample, 0],
        velocity_xy[sample, 1],
        speed[sample],
        cmap="viridis",
        width=0.0015,
        scale=max_speed * 60.0,
        minlength=0.0,
        alpha=0.85,
    )
    ax.set_title("Cell-centered velocity vectors")

    for ax in axes:
        ax.set_aspect("equal", adjustable="box")
        ax.set_xlim(0.0, lx)
        ax.set_ylim(0.0, ly)
        ax.set_xlabel("x (m)")
    axes[0].set_ylabel("y (m)")
    fig.tight_layout()
    fig.savefig(OUT / "random_openfoam_flow.png")
    plt.close(fig)

    return {
        "cells": int(centers_xy.shape[0]),
        "area_sum": float(np.sum(areas[good])),
        "mean_ux": mean_ux,
        "mean_uy": mean_uy,
        "mean_speed": mean_speed,
        "max_speed": max_speed,
        "target_ux": UBAR,
        "mean_ux_over_target": mean_ux / UBAR,
        "max_speed_over_target": max_speed / UBAR,
    }


def write_report(geometry: dict, metrics: dict) -> None:
    check_tail = read_log_tail("log.checkMesh", n=45)
    simple_tail = read_log_tail("log.simpleFoam", n=55)
    shift = geometry.get("openfoam_origin_shift", {})
    if shift.get("enabled"):
        shift_text = (
            f"- OpenFOAM periodic-window shift: x_cut={shift['x_cut'] * 1e6:.2f} um, "
            f"y_cut={shift['y_cut'] * 1e6:.2f} um\n"
            f"- Boundary cut clearances after shift: x={shift['x_boundary_clearance'] * 1e6:.2f} um, "
            f"y={shift['y_boundary_clearance'] * 1e6:.2f} um"
        )
    else:
        shift_text = "- OpenFOAM periodic-window shift: disabled"
    report = f"""# Random porous OpenFOAM flow

The random periodic disk geometry has been converted into a 2D OpenFOAM case
with cyclic boundaries in x and y, empty front/back planes, no-slip grain
walls, laminar transport, and the selected forcing mode in the x direction.

## Geometry and mesh setup

- Geometry source: `{GEOMETRY_PATH.relative_to(ROOT)}`
- Case directory: `{CASE.relative_to(ROOT)}`
- Domain: {geometry['domain']['length_x'] * 1e3:.3f} mm x {geometry['domain']['length_y'] * 1e3:.3f} mm
- Grains: {len(geometry['grains'])}
- Porosity: {geometry['derived']['actual_porosity']:.3f}
- Mesh backend: {MESH_BACKEND}
- Base mesh: {BASE_CELLS_X} x {BASE_CELLS_Y} x {Z_CELLS}
- True 2D empty-patch formulation: {TWO_D_EMPTY}
- Surface refinement level: {SURFACE_REFINEMENT}
- Snapping enabled: {SNAP_MESH}
- Gmsh near-wall/far mesh sizes: {GMSH_SIZE_WALL:.3e} / {GMSH_SIZE_FAR:.3e} m
- Flow forcing mode: {FORCING_MODE}
- Body acceleration when used: {BODY_ACCEL:.6e} m/s2
- Kinematic viscosity: {NU:.3e} m2/s
- Target mean velocity: {UBAR:.6e} m/s ({TARGET_M_PER_DAY:.2f} m/day)
{shift_text}

## Parsed VTU flow metrics

- Parsed cell count: {metrics['cells']:,}
- Area represented by parsed cells: {metrics['area_sum']:.6e} m2
- Area-weighted mean ux: {metrics['mean_ux']:.6e} m/s
- Area-weighted mean uy: {metrics['mean_uy']:.6e} m/s
- Mean ux / target ux: {metrics['mean_ux_over_target']:.4f}
- Area-weighted mean speed: {metrics['mean_speed']:.6e} m/s
- Maximum cell speed: {metrics['max_speed']:.6e} m/s
- Maximum speed / target ux: {metrics['max_speed_over_target']:.3f}

## checkMesh tail

```text
{check_tail}
```

## simpleFoam tail

```text
{simple_tail}
```

## Output

- `random_openfoam_flow.png`: speed and vector diagnostic
- `case/VTK`: OpenFOAM VTU export for the latest time
"""
    (OUT / "random_openfoam_flow_report.md").write_text(report, encoding="utf-8")


def main() -> None:
    args = parse_args()
    configure_from_args(args)
    OUT.mkdir(parents=True, exist_ok=True)
    geometry = load_geometry()
    if args.reuse_mesh:
        if not (CASE / "constant" / "polyMesh").exists():
            raise FileNotFoundError("Cannot reuse mesh because case/constant/polyMesh is missing")
        write_force_options()
        remove_solution_times()
    else:
        write_case(geometry)
    run_openfoam_case(geometry, reuse_mesh=args.reuse_mesh)
    vtu = find_vtu_file()
    centers, velocity, areas = parse_xml_vtu(vtu)
    metrics = draw_flow_figure(geometry, centers, velocity, areas)
    write_report(geometry, metrics)
    print(OUT / "random_openfoam_flow_report.md")
    print(OUT / "random_openfoam_flow.png")


if __name__ == "__main__":
    main()
